spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.url= jdbc:postgresql://localhost:5432/blog-back-app
#spring.datasource.url=jdbc:postgresql://postgres:5432/blog-back-app
spring.datasource.username= user
spring.datasource.password= 123

#app.upload-dir = ${UPLOAD_DIR:uploads}
app.upload-dir = /Users/dev/Downloads/uploads
app.upload-dir.allowed-image-extensions = .jpg, .jpeg, .png, .webp

